//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share_a_Ton {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Share_a_Ton.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a folder to which all of you&apos;re files will be saved!.
        /// </summary>
        internal static string ChooseFileString {
            get {
                return ResourceManager.GetString("ChooseFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve chosen a directory, please only drag and drop files!.
        /// </summary>
        internal static string DirectoryDraggedErrorString {
            get {
                return ResourceManager.GetString("DirectoryDraggedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to drop the file on one of the computers in the LAN list!.
        /// </summary>
        internal static string DragLocationErrorString {
            get {
                return ResourceManager.GetString("DragLocationErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop the file on the LAN PC you want to send the file to!.
        /// </summary>
        internal static string DragTipString {
            get {
                return ResourceManager.GetString("DragTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your download folder has been deleted, please specify a new one..
        /// </summary>
        internal static string FileDeletedWarning {
            get {
                return ResourceManager.GetString("FileDeletedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please drag one file at a time!.
        /// </summary>
        internal static string MultipleFilesDraggedErrorString {
            get {
                return ResourceManager.GetString("MultipleFilesDraggedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and download folder path are mandatory!.
        /// </summary>
        internal static string OptionsUsernameOrDownloadFolderErrorString {
            get {
                return ResourceManager.GetString("OptionsUsernameOrDownloadFolderErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued!.
        /// </summary>
        internal static string Queued {
            get {
                return ResourceManager.GetString("Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving from :.
        /// </summary>
        internal static string ReceivingFrom {
            get {
                return ResourceManager.GetString("ReceivingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending to :.
        /// </summary>
        internal static string SendTo {
            get {
                return ResourceManager.GetString("SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer aborted....
        /// </summary>
        internal static string TransferAborted {
            get {
                return ResourceManager.GetString("TransferAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer completed!.
        /// </summary>
        internal static string TransferCompleted {
            get {
                return ResourceManager.GetString("TransferCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring data....
        /// </summary>
        internal static string TransferInProgress {
            get {
                return ResourceManager.GetString("TransferInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer rejected!.
        /// </summary>
        internal static string TransferRejected {
            get {
                return ResourceManager.GetString("TransferRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer started!.
        /// </summary>
        internal static string TransferStarted {
            get {
                return ResourceManager.GetString("TransferStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer terminated!.
        /// </summary>
        internal static string TransferTerminated {
            get {
                return ResourceManager.GetString("TransferTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TransferViewClose {
            get {
                return ResourceManager.GetString("TransferViewClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string TransferViewOkay {
            get {
                return ResourceManager.GetString("TransferViewOkay", resourceCulture);
            }
        }
    }
}
